SGCFT.Apresentacao/Controllers/PerguntaController.cs
using SGCFT.Apresentacao.Models;
using SGCFT.Dados.Repositorios;
using SGCFT.Dominio.Contratos.Repositorios;
using SGCFT.Dominio.Contratos.Servicos;
using SGCFT.Dominio.Entidades;
using SGCFT.Dominio.Servicos;
using SGCFT.Utilitario;
using System.Linq;
using System.Web.Mvc;

namespace SGCFT.Apresentacao.Controllers
{
    [Authorize]
    public class PerguntaController: BaseController
    {
        private readonly IPerguntaServico _servicoPerguntas;
        private readonly IPerguntaRepositorio _perguntaRepositorio;
        private readonly ITreinamentoRepositorio _treinamentoRepositorio;
        public PerguntaController()
        {
            _perguntaRepositorio = new PerguntaRepositorio();
            _servicoPerguntas = new PerguntaServico(_perguntaRepositorio);
            _treinamentoRepositorio = new TreinamentoRepositorio();
        }

        public ActionResult Index()
        {
            PerguntaViewModel perguntaViewModel = IniciarCadastro();
            return View(perguntaViewModel);

        }

        [HttpPost]
        public ActionResult Index(PerguntaViewModel perguntaViewModel)
        {
            Retorno retorno = null;
            if (ModelState.IsValid)
            {
                Pergunta pergunta = perguntaViewModel.ConverterParaDominio();
                pergunta.IdAutor = base.IdUsuarioAutenticado;

                for (int i = 0; i < perguntaViewModel.Alternativas.Length; i++)
                {
                    pergunta.AdicionarAlternativa(perguntaViewModel.Alternativas[i], perguntaViewModel.Corretos[i]);
                }

                retorno = _servicoPerguntas.InserirPergunta(pergunta);
                ViewBag.Sucesso = retorno.Sucesso;
                ViewBag.Mensagens = retorno.Mensagens;
            }
            return Json(retorno);
        }

        public JsonResult ObterQuestionario(int idModulo)
        {
            var perguntas = _perguntaRepositorio.SelecionarPorIdModulo(idModulo);
            var questionarios = perguntas.Select(x => new QuestionarioViewModel(x)).ToList();
            return Json(questionarios, JsonRequestBehavior.AllowGet);
        }

        private PerguntaViewModel IniciarCadastro()
        {
            PerguntaViewModel perguntaViewModel = new PerguntaViewModel();
            var treinamentos = _treinamentoRepositorio.selecionarTreinamentosPorUsuario(base.IdUsuarioAutenticado);
            perguntaViewModel.Treinamentos = treinamentos.Select(x => new TreinamentoViewModel(x)).ToList();
            return perguntaViewModel;
        }
    }
}

SGCFT.Apresentacao/Controllers/TreinamentoController.cs
using SGCFT.Apresentacao.Models;
using SGCFT.Dados.Repositorios;
using SGCFT.Dominio.Contratos.Repositorios;
using SGCFT.Dominio.Contratos.Servicos;
using SGCFT.Dominio.Entidades;
using SGCFT.Dominio.Servicos;
using SGCFT.Utilitario;
using System.Web.Mvc;

namespace SGCFT.Apresentacao.Controllers
{
    [Authorize]
    public class TreinamentoController: BaseController
    {
        private readonly ITreinamentoServico _servicoTreinamentos;
        private readonly ITreinamentoRepositorio _repositorioTreinamentos;

        public TreinamentoController()
        {
            _servicoTreinamentos = new TreinamentoServico(new TreinamentoRepositorio());
            _repositorioTreinamentos = new TreinamentoRepositorio();
        }

        public ActionResult Novo()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Novo(TreinamentoViewModel treinamentoViewModel)
        {
            Retorno retorno = null;
            if (ModelState.IsValid)
            {
                Treinamento treinamento = treinamentoViewModel.ConverterParaDominio();
                treinamento.IdAutor = base.IdUsuarioAutenticado;

                treinamentoViewModel.Modulos.ForEach(x => treinamento.AdicionarModulo(x));

                retorno = _servicoTreinamentos.InserirTreinamento(treinamento);
            }
            return Json(retorno);
        }

        public ActionResult Editar(int id)
        {
            TreinamentoViewModel treinamentoViewModel = new TreinamentoViewModel();
            var treinamento = _repositorioTreinamentos.ObterPorId(id);
            treinamentoViewModel.Tema = treinamento.Tema;
            treinamentoViewModel.TipoTreinamento = treinamento.TipoTreinamento;

            return View(treinamentoViewModel);
        }

        [HttpGet]
        [Route("Treinamento/{tema}/{id}")]
        public ActionResult Exibicao(string tema, int id)
        {
            var treinamento = _repositorioTreinamentos.ObterParaExibicao(id);
            var exibicao = new TreinamentoExibicaoViewModel(treinamento.Id, treinamento.Tema, "", treinamento.Duracao, treinamento.Autor.Nome, treinamento.Modulos);
            return View(exibicao);
        }
    }
}

SGCFT.Apresentacao/Controllers/UsuarioController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.AspNet.Identity.Owin;
using SGCFT.Apresentacao.Models;
using SGCFT.Dados.Repositorios;
using SGCFT.Dominio.Contratos.Servicos;
using SGCFT.Dominio.Entidades;
using SGCFT.Dominio.Servicos;
using SGCFT.Seguranca.Contexto;
using SGCFT.Seguranca.Manager;
using SGCFT.Utilitario;
using System.Web;
using System.Web.Mvc;

namespace SGCFT.Apresentacao.Controllers
{
    public class UsuarioController : BaseController
    {
        private readonly IUsuarioServico _servicoUsuarios;

        public UsuarioController()
        {
            this._servicoUsuarios = new UsuarioServico(new UsuarioRepositorio());
        }

        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index(UsuarioViewModel usuarioViewModel)
        {
            if (ModelState.IsValid)
            {
                Usuario usuario = usuarioViewModel.ConverterParaDominio();
                Retorno retorno = _servicoUsuarios.InserirUsuario(usuario);
                ViewBag.Sucesso = retorno.Sucesso;
                ViewBag.Mensagens = retorno.Mensagens;

                if(retorno.Sucesso)
                {
                    var login = new LoginViewModel()
                    {
                        Login = usuario.Email,
                        Senha = usuario.Senha
                    };

                    return Login(login);
                }
            }

            return Login();
        }

        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(LoginViewModel loginViewModel)
        {
            var userManager = HttpContext.GetOwinContext().GetUserManager<UserAppManager>();

            var user = userManager.Find(loginViewModel.Login, loginViewModel.Senha);

            if (user != null)
            {
                var appAsign = HttpContext.GetOwinContext().Get<AppSignInManager>();
                appAsign.SignIn(user, false, false);

                return RedirectToAction("Index", "Home");
            }
            else
            {
                ViewBag.Mensagem = "Usuário ou senha estão incorretos";
                return View(loginViewModel);
            }
        }

        public ActionResult Logout()
        {
            var authenticationManager = HttpContext.GetOwinContext().Authentication;
            authenticationManager.SignOut();
            return RedirectToAction("Index", "Home");
        }

    }
}

SGCFT.Apresentacao/Controllers/VideoController.cs
using SGCFT.Apresentacao.Models;
using SGCFT.Dados.Repositorios;
using SGCFT.Dominio.Contratos.Repositorios;
using SGCFT.Dominio.Contratos.Servicos;
using SGCFT.Dominio.Entidades;
using SGCFT.Dominio.Servicos;
using SGCFT.Utilitario;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace SGCFT.Apresentacao.Controllers
{
    [Authorize]
    public class VideoController: BaseController
    {
        private readonly IVideoServico _servicoVideos;
        private readonly ITreinamentoRepositorio _treinamentoRepositorio;
        private readonly IVideoRepositorio _videoRepositorio;

        public VideoController()
        {
            _servicoVideos = new VideoServico(new VideoRepositorio());
            _treinamentoRepositorio = new TreinamentoRepositorio();
            _videoRepositorio = new VideoRepositorio();
        }

        public ActionResult Index()
        {
            VideoViewModel videoViewModel = IniciarCadastro();
            return View(videoViewModel);
        }

        private VideoViewModel IniciarCadastro()
        {
            VideoViewModel videoViewModel = new VideoViewModel();
            var treinamentos = _treinamentoRepositorio.selecionarTreinamentosPorUsuario(base.IdUsuarioAutenticado);
            videoViewModel.Treinamentos = treinamentos.Select(x => new TreinamentoViewModel(x)).ToList();
            return videoViewModel;
        }

        [HttpPost]
        public ActionResult Index(VideoViewModel videoViewModel)
        {
            if (ModelState.IsValid)
            {
                Video video = videoViewModel.ConverterParaDominio();
                Retorno retorno = _servicoVideos.InserirVideo(video);
                ViewBag.Sucesso = retorno.Sucesso;
                ViewBag.Mensagens = retorno.Mensagens;
            }
            var videoViewModelNovo = IniciarCadastro();
            return View(videoViewModelNovo);
        }

        [HttpGet]
        [Route("Video/modulo-{modulo}/{idModulo}")]
        public ActionResult Exibicao(string modulo, int idModulo)
        {
            var video = _videoRepositorio.ObterVideoPorIdModulo(idModulo);

            object retorno = null;// new TreinamentoExibicaoViewModel(video.Id, video.Modulo.Treinamento.Tema, video.Modulo.Titulo, video.Titulo, video.IdModulo);

            return View(retorno);
        }

        [HttpGet]
        [Route("Video/conteudo/{titulo}/{id}")]
        public FileResult ExibirConteudo(string titulo, int id)
        {
            var video = _videoRepositorio.ObterConteudoVideoPorId(id);
            return File(video, "video/mp4", $"{titulo}.mp4");
        }

    }
}

SGCFT.Apresentacao/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800%7CMuli:100,300,400,600,800">
    <link type="text/css" href="~/Content/fonts.css" rel="stylesheet" />
    <link type="text/css" href="~/Content/style.css" rel="stylesheet" />
    @RenderSection("styles", required: false)
    <style>
        .ie-panel {
            display: none;
            background: #212121;
            padding: 10px 0;
            box-shadow: 3px 3px 5px 0 rgba(0,0,0,.3);
            clear: both;
            text-align: center;
            position: relative;
            z-index: 1;
        }

        html.ie-10 .ie-panel, html.lt-ie-10 .ie-panel {
            display: block;
        }
    </style>
</head>
<body>
    <div class="preloader" id="loading">
        <div class="preloader-body">
            <div id="loading-center-object">
                <div class="object" id="object_four"></div>
                <div class="object" id="object_three"></div>
                <div class="object" id="object_two"></div>
                <div class="object" id="object_one"></div>
            </div>
        </div>
    </div>
    <div class="page">
        <header class="section page-header" id="header-page">
            <!-- RD Navbar-->
            <div class="rd-navbar-wrap">
                <nav class="rd-navbar rd-navbar-modern" data-layout="rd-navbar-fixed" data-sm-layout="rd-navbar-fixed" data-md-layout="rd-navbar-fixed" data-md-device-layout="rd-navbar-fixed" data-lg-layout="rd-navbar-fixed" data-lg-device-layout="rd-navbar-fixed" data-xl-layout="rd-navbar-static" data-xl-device-layout="rd-navbar-static" data-xxl-layout="rd-navbar-static" data-xxl-device-layout="rd-navbar-static" data-lg-stick-up-offset="10px" data-xl-stick-up-offset="10px" data-xxl-stick-up-offset="10px" data-lg-stick-up="true" data-xl-stick-up="true" data-xxl-stick-up="true">
                    <div class="rd-navbar-main">
                        <!-- RD Navbar Panel-->
                        <div class="rd-navbar-panel">
                            <!-- RD Navbar Toggle-->
                            <button class="rd-navbar-toggle" data-rd-navbar-toggle=".rd-navbar-nav-wrap"><span></span></button>
                            <!-- RD Navbar Brand-->
                            <div class="rd-navbar-brand">
                                <a class="brand" href="@Url.Action("Index", "Home")">
                                    <img src="~/Content/images/logo.png" alt="" width="148" height="31" />
                                </a>
                            </div>
                        </div>
                        <div class="rd-navbar-nav-wrap">
                            <!-- RD Navbar Nav-->
                            <ul class="rd-navbar-nav">
                                <li class="rd-nav-item active">@Html.ActionLink("Home", "Index", "Home", null, new { @class = "rd-nav-link" })</li>
                                @if (this.Request.IsAuthenticated)
                                {
                                    <li class="rd-nav-item">@Html.ActionLink("Cadastrar treinamento", "Novo", "Treinamento", null, new { @class = "rd-nav-link" })</li>
                                    <li class="rd-nav-item">@Html.ActionLink("Cadastrar pergunta", "Index", "Pergunta", null, new { @class = "rd-nav-link" })</li>
                                    <li class="rd-nav-item">@Html.ActionLink("Cadastrar video", "Index", "Video", null, new { @class = "rd-nav-link" })</li>
                                }
                            </ul>
                        </div>
                        <div class="rd-navbar-element">
                            @if (this.Request.IsAuthenticated)
                            {
                                <a class="button button-sm button-header button-winona" href="@Url.Action("Logout", "Usuario")">Sair</a>
                            }
                            else
                            {
                                <a class="button button-sm button-header button-winona" href="@Url.Action("Login", "Usuario")">Login / Cadastra-se</a>
                            }
                        </div>
                        <div class="rd-navbar-dummy"></div>
                    </div>
                </nav>
            </div>
        </header>
        @RenderBody()
        <footer class="section footer-classic">
            <div class="footer-classic-main">
                <div class="container">
                    <div class="row row-50 justify-content-lg-between">
                        <div class="col-sm-7 col-lg-3 col-xl-2">
                            <a class="brand" href="index.html"><img src="~/Content/images/logo.png" alt="" width="148" height="31" /></a>
                            <p><span style="max-width: 250px;">Desde 2015 ajudando pessoas físicas e jurídicas no desafio de treinar.</span></p>
                        </div>
                        <div class="col-sm-5 col-lg-3 col-xl-2">
                            <h4 class="footer-classic-title">Quem Somos</h4>
                            <ul class="list footer-classic-list">
                                <li><a href="about-us.html">Sobre Nós</a></li>
                                <li><a href="#">Carreia</a></li>
                                <li><a href="#">Nosso Time</a></li>
                            </ul>
                        </div>
                        <div class="col-sm-7 col-lg-5 col-xl-3">
                            <h4 class="footer-classic-title">Links Rápidos</h4>
                            <ul class="list footer-classic-list">
                                <li><a href="#">Treinamentos</a></li>
                                <li><a href="#">Perguntas</a></li>
                            </ul>
                        </div>
                        <div class="col-sm-5 col-lg-9 col-xl-2">
                            <h4 class="footer-classic-title">Entre em contato</h4>
                            <div class="row row-20 row-sm-35">
                                <div class="col-6 col-sm-12 col-lg-8 col-xl-12">
                                    <div class="row row-10 text-default">
                                        <div class="col-lg-6 col-xl-12"><a href="mailto:#">contato@tractus.br</a></div>
                                        <div class="col-lg-6 col-xl-12"><a class="big" href="tel:#">+1-853-234-65</a></div>
                                    </div>
                                </div>
                                <div class="col-6 col-sm-12 col-lg-4 col-xl-12 text-right text-sm-left">
                                    <div class="group group-xs"><a class="link link-social-1 mdi mdi-twitter" href="https://www.twitter.com/tractusplat"></a><a class="link link-social-1 mdi mdi-facebook" href="https://www.facebook.com/tractusplat"></a><a class="link link-social-1 mdi mdi-instagram" href="https://www.instagram.com/tractusplat/"></a></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="footer-classic-aside">
                <div class="container">
                    <p class="rights"><span>&copy;&nbsp;</span><span class="copyright-year"></span><span>&nbsp;</span><span>Businet</span>. All Rights Reserved. Design by <a href="https://www.templatemonster.com">TemplateMonster</a></p>
                </div>
            </div>
        </footer>
    </div>
    <div class="snackbars" id="form-output-global"></div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <script src="~/Scripts/core.min.js" type="text/javascript"></script>
    <script src="~/Scripts/script-custom.js" type="text/javascript"></script>
    @RenderSection("scripts", required: false)
</body>
</html>