SGCFT.Apresentacao/Models/TreinamentoViewModel.cs
using SGCFT.Dominio.Entidades;
using SGCFT.Utilitario;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace SGCFT.Apresentacao.Models
{
    public class TreinamentoViewModel
    {
        public TreinamentoViewModel()
        {

        }

        public TreinamentoViewModel(Treinamento treinamento)
        {
            Id = treinamento.Id;
            Tema = treinamento.Tema;
            IdAutor = treinamento.IdAutor;
            TipoTreinamento = treinamento.TipoTreinamento;
            Senha = treinamento.Senha;
        }

        public int Id { get; set; }
        [Required(ErrorMessage = "Informe o tema")]
        public string Tema { get; set; }
        public int IdAutor { get; set; }
        [Required(ErrorMessage = "Informe o tipo do treinamento")]
        [Range(1, int.MaxValue, ErrorMessage = "Selecione um tipo correto")]
        public EnumTipoTreinamento TipoTreinamento { get; set; }
        public string Senha { get; set; }
        public List<string> Modulos { get; set; }
        public Treinamento ConverterParaDominio()
        {
            Treinamento treinamento = new Treinamento(this.Tema, this.IdAutor, this.TipoTreinamento, this.Senha);
            return treinamento;
        }


    }
}

SGCFT.Apresentacao/Controllers/ModuloController.cs
using SGCFT.Apresentacao.Models;
using SGCFT.Dados.Repositorios;
using SGCFT.Dominio.Contratos.Repositorios;
using SGCFT.Dominio.Contratos.Servicos;
using SGCFT.Dominio.Entidades;
using SGCFT.Dominio.Servicos;
using SGCFT.Utilitario;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SGCFT.Apresentacao.Controllers
{
    [Authorize]
    public class ModuloController: BaseController
    {
        private readonly IModuloServico _servicoModulos;
        private readonly ITreinamentoRepositorio _treinamentoRepositorio;
        private readonly IModuloRepositorio _moduloRepositorio;

        public ModuloController()
        {
            _servicoModulos = new ModuloServico(new ModuloRepositorio());
            _treinamentoRepositorio = new TreinamentoRepositorio();
            _moduloRepositorio = new ModuloRepositorio();
        }
        
        [HttpGet]
        [Route("Modulo/GetDropDown/{idTreinamento}")]
        public JsonResult GetDropDown(int idTreinamento)
        {
            var lista = _moduloRepositorio.SelecionarPorIdTreinamento(idTreinamento);
            return Json(lista, JsonRequestBehavior.AllowGet);
        }

        [Route("Modulo/{titulo}/{id}")]
        public ActionResult Exibicao(string titulo, int id)
        {
            var modulo = _moduloRepositorio.ObterModuloPorIdParaExibicao(id, base.IdUsuarioAutenticado);
            var exibicao = new ModuloExibicaoViewModel(modulo.Id, modulo.Titulo, modulo.Videos);
            return View(exibicao);
        }
    }
}

SGCFT.Apresentacao/Controllers/TreinamentoController.cs
using SGCFT.Apresentacao.Models;
using SGCFT.Dados.Repositorios;
using SGCFT.Dominio.Contratos.Repositorios;
using SGCFT.Dominio.Contratos.Servicos;
using SGCFT.Dominio.Entidades;
using SGCFT.Dominio.Servicos;
using SGCFT.Utilitario;
using System.Web.Mvc;

namespace SGCFT.Apresentacao.Controllers
{
    [Authorize]
    public class TreinamentoController: BaseController
    {
        private readonly ITreinamentoServico _servicoTreinamentos;
        private readonly ITreinamentoRepositorio _repositorioTreinamentos;

        public TreinamentoController()
        {
            _servicoTreinamentos = new TreinamentoServico(new TreinamentoRepositorio());
            _repositorioTreinamentos = new TreinamentoRepositorio();
        }

        public ActionResult Novo()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Novo(TreinamentoViewModel treinamentoViewModel)
        {
            Retorno retorno = null;
            if (ModelState.IsValid)
            {
                Treinamento treinamento = treinamentoViewModel.ConverterParaDominio();
                treinamento.IdAutor = base.IdUsuarioAutenticado;

                treinamentoViewModel.Modulos.ForEach(x => treinamento.AdicionarModulo(x));

                retorno = _servicoTreinamentos.InserirTreinamento(treinamento);
            }
            return Json(retorno);
        }

        public ActionResult Editar(int id)
        {
            TreinamentoViewModel treinamentoViewModel = new TreinamentoViewModel();
            var treinamento = _repositorioTreinamentos.ObterPorId(id);
            treinamentoViewModel.Tema = treinamento.Tema;
            treinamentoViewModel.TipoTreinamento = treinamento.TipoTreinamento;

            return View(treinamentoViewModel);
        }

        [HttpGet]
        [Route("Treinamento/{tema}/{id}")]
        public ActionResult Exibicao(string tema, int id)
        {
            var treinamento = _repositorioTreinamentos.ObterParaExibicao(id);
            var exibicao = new TreinamentoExibicaoViewModel(treinamento.Id, treinamento.Tema, "", treinamento.Duracao, treinamento.Autor.Nome, treinamento.Modulos);
            return View(exibicao);
        }
    }
}

SGCFT.Apresentacao/Controllers/VideoController.cs
using SGCFT.Apresentacao.Models;
using SGCFT.Dados.Repositorios;
using SGCFT.Dominio.Contratos.Repositorios;
using SGCFT.Dominio.Contratos.Servicos;
using SGCFT.Dominio.Entidades;
using SGCFT.Dominio.Servicos;
using SGCFT.Utilitario;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace SGCFT.Apresentacao.Controllers
{
    [Authorize]
    public class VideoController: BaseController
    {
        private readonly IVideoServico _servicoVideos;
        private readonly ITreinamentoRepositorio _treinamentoRepositorio;
        private readonly IVideoRepositorio _videoRepositorio;

        public VideoController()
        {
            _servicoVideos = new VideoServico(new VideoRepositorio());
            _treinamentoRepositorio = new TreinamentoRepositorio();
            _videoRepositorio = new VideoRepositorio();
        }

        public ActionResult Index()
        {
            VideoViewModel videoViewModel = IniciarCadastro();
            return View(videoViewModel);
        }

        private VideoViewModel IniciarCadastro()
        {
            VideoViewModel videoViewModel = new VideoViewModel();
            var treinamentos = _treinamentoRepositorio.selecionarTreinamentosPorUsuario(base.IdUsuarioAutenticado);
            videoViewModel.Treinamentos = treinamentos.Select(x => new TreinamentoViewModel(x)).ToList();
            return videoViewModel;
        }

        [HttpPost]
        public ActionResult Index(VideoViewModel videoViewModel)
        {
            if (ModelState.IsValid)
            {
                Video video = videoViewModel.ConverterParaDominio();
                Retorno retorno = _servicoVideos.InserirVideo(video);
                ViewBag.Sucesso = retorno.Sucesso;
                ViewBag.Mensagens = retorno.Mensagens;
            }
            var videoViewModelNovo = IniciarCadastro();
            return View(videoViewModelNovo);
        }

        [HttpGet]
        [Route("Video/modulo-{modulo}/{idModulo}")]
        public ActionResult Exibicao(string modulo, int idModulo)
        {
            var video = _videoRepositorio.ObterVideoPorIdModulo(idModulo);

            object retorno = null;// new TreinamentoExibicaoViewModel(video.Id, video.Modulo.Treinamento.Tema, video.Modulo.Titulo, video.Titulo, video.IdModulo);

            return View(retorno);
        }

        [HttpGet]
        [Route("Video/conteudo/{titulo}/{id}")]
        public FileResult ExibirConteudo(string titulo, int id)
        {
            var video = _videoRepositorio.ObterConteudoVideoPorId(id);
            return File(video, "video/mp4", $"{titulo}.mp4");
        }

    }
}

SGCFT.Apresentacao/Views/Treinamento/Exibicao.cshtml
@model SGCFT.Apresentacao.Models.TreinamentoExibicaoViewModel
@{
    ViewBag.Title = $"Treinamento: {Model.Tema}";
}

<section class="section section-xl bg-accent">
    <div class="container">
        <div class="row row-50 justify-content-center flex-lg-row-reverse align-items-center justify-content-lg-between">
            <div class="col-sm-10 col-lg-5 wow fadeInRightSmall">
                <div class="badge">Autor: @Model.NomeAutor</div>
                <h3>Tema: @Model.Tema</h3>
                <p class="big inset-2">@Model.DescricaoTreinamento</p>
            </div>
            <div class="col-sm-10 col-lg-6 wow fadeInLeftSmall">
                <div class="thumbnail-classy">
                    <div class="thumbnail-classy-image bg-image"></div>
                    <div class="thumbnail-classy-caption">
                        <a class="thumbnail-classy-button mdi mdi-play" href="@Url.Action("Exibicao", "Modulo", new { titulo = Model.TituloModuloInicial, id = Model.IdModuloInicial })">
                            <svg class="thumbnail-classy-button-shape" width="86" height="86" viewbox="0 0 88 88" xmlns="http://www.w3.org/2000/svg" shape-rendering="crispEdges">
                                <rect x="1" y="1" width="86" height="86" rx="6" ry="6"></rect>
                            </svg>
                        </a>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <h3>Módulos</h3>
            </div>
            @foreach (var item in Model.Modulos)
            {
                <a class="col-md-2 button button-primary button-shadow button-winona font-weight-sbold btn-space" href="@Url.Action("Exibicao", "Modulo", new { titulo = item.Titulo.ToURLCustomizada(), id = item.Id })">@item.Titulo</a>
            }
        </div>
    </div>
</section>

SGCFT.Apresentacao/Views/Treinamento/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

SGCFT.Apresentacao/Views/Treinamento/Novo.cshtml
@model SGCFT.Apresentacao.Models.TreinamentoViewModel
@{

    ViewBag.Title = "Cadastro de Treinamento";
}

@section scripts
{
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/unobtrusive")
    <script type="text/javascript">
        $(document).ready(function () {
            $("#btnAdicionarModulo").click(function () {
                if ($("#txtAdicionarModulo").val() != "") {
                    var conteudo = document.getElementById("template-modulo").innerHTML;
                    conteudo = conteudo.replace("{{modulo}}", $("#txtAdicionarModulo").val());
                    conteudo = conteudo.replace("{{idModulo}}", 0);
                    $("#tabelaModulo").find("tbody").append(conteudo);
                    $("#txtAdicionarModulo").val("");
                    $("#txtAdicionarModulo").focus();
                }
            });
        });

        function removerLinhaModulo(botao) {
            var linha = $(botao).parents("tr");
            linha.hide('slow', function () { linha.remove(); });
        }

        function sucesso(data) {
            if (data.Sucesso) {
                $("#mensagemSucesso").show('slow');
                $('html, body').animate({ scrollTop: $('#header-page').offset().top }, 'slow');
            } else {
                $(data.Mensagens).each(function () {
                    $("#mensagemFalha").html("");
                    var mensagem = this + "<br />";
                    $("#mensagemFalha").append(mensagem);
                });
                $("#mensagemFalha").show('slow');
            }
        }

        function falha(data) {
            $("#mensagemFalha").html("Erro ao cadastrar o treinamento");
            $("#mensagemFalha").show('slow');
        }

    </script>
}

<section class="section section-md bg-gray-100">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="card border-0">
                    <div class="card-header">
                        <h3 class="text-center"><i class="fas fa-plus-circle"></i> Novo Cadastro de Treinamento</h3>
                    </div>
                    <div class="card-body">

                        <div class="alert alert-success" style="display: none;" id="mensagemSucesso" role="alert">Treinamento cadastrado com sucesso. @Html.ActionLink("Clique aqui", "Index", "Video") para cadastrar os vídeos.</div>
                        <div class="alert alert-danger" style="display: none;" id="mensagemFalha" role="alert">
                        </div>

                        @using (Ajax.BeginForm("Novo", "Treinamento", new AjaxOptions() { HttpMethod = "POST", OnSuccess = "sucesso", OnFailure = "falha" }, new { id = "formTreinamento", @class = "rd-form" }))
                        {
                            <div class="form-row mt-2">
                                <div class="form-group col-lg-4">
                                    <label for="txtTema">Tema</label>
                                    @Html.TextBoxFor(x => x.Tema, new { id = "txtTema", @class = "form-input", autocomplete = "off" })
                                    <span class="warning d-inline">@Html.ValidationMessageFor(x => x.Tema)</span>
                                </div>
                                <div class="form-group col-lg-4">
                                    <label for="ddlTipoTreinamento">Tipo de treinamento</label>
                                    @Html.EnumDropDownListFor(x => x.TipoTreinamento, "Selecione um tipo", new { id = "ddlTipoTreinamento", @class = "form-control form-select" })
                                    <span class="warning d-inline">@Html.ValidationMessageFor(x => x.TipoTreinamento)</span>
                                </div>
                                <div class="form-group col-lg-4">
                                    <label for="txtSenha">Senha</label>
                                    @Html.TextBoxFor(x => x.Senha, new { id = "txtSenha", @class = "form-input", autocomplete = "off" })
                                    <span class="warning d-inline">@Html.ValidationMessageFor(x => x.Senha)</span>
                                </div>
                                <div class="form-group col-lg-12">
                                    <h4 class="text-center">Informe abaixo os módulos de seu treinamento</h4>
                                    <div class="table-responsive">
                                        <table class="table table-striped table-bordered table-sm" id="tabelaModulo" cellspacing="0" width="100%">
                                            <thead>
                                                <tr>
                                                    <th>
                                                        <input type="text" class="form-input" id="txtAdicionarModulo" placeholder="informe o nome do módulo" />
                                                    </th>
                                                    <th>
                                                        <button type="button" class="btn btn-sm btn-success" aria-label="Success" id="btnAdicionarModulo"><spam class="fas fa-plus-circle"></spam> Adicionar</button>
                                                    </th>
                                                </tr>
                                            </thead>
                                            <tbody></tbody>
                                        </table>
                                    </div>
                                </div>
                                <div class="text-right">
                                    <a href="@Url.Action("Index")" class="btn btn-outline-secondary btn-sm" role="button" aria-label="Voltar para a página anterior" id="btnVoltar">
                                        <i class="fas fa-undo"></i> Voltar
                                    </a>
                                    <button class="btn btn-sm btn-outline-success" type="submit" aria-label="Salvar" id="btnSalvar">
                                        <i class="fas fa-check-circle"></i> Salvar
                                    </button>
                                </div>

                                @Html.AntiForgeryToken()
                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script type="text/template" id="template-modulo">
        <tr>
            <td>
                <input type="text" value="{{modulo}}" class="form-input" name="Modulos" />
            </td>
            <td>
                <button id="{{idModulo}}" type="button" class="btn btn-sm btn-danger" style="height:100%;width:100px" aria-label="Danger" onclick="removerLinhaModulo(this);"><span class="fas fa-trash-alt"></span> Excluir</button>
            </td>
        </tr>
    </script>

</section>