SGCFT.Apresentacao/Models/ModuloViewModel.cs
using SGCFT.Dominio.Entidades;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace SGCFT.Apresentacao.Models
{
    public class ModuloViewModel
    {
        public ModuloViewModel()
        {

        }

        public ModuloViewModel(int id, string titulo)
        {
            this.Id = id;
            this.Titulo = titulo;
        }

        public int Id { get; set; }
        public int IdTreinamento { get; set; }
        [Required(ErrorMessage = "Informe o título")]
        public string Titulo { get; set; }
        public List<TreinamentoViewModel> ListaTreinamentos { get; set; }

        public Modulo ConverterParaDominio()
        {
            Modulo modulo = new Modulo(this.IdTreinamento, this.Titulo);
            return modulo;
        }


    }
}

SGCFT.Apresentacao/Controllers/ModuloController.cs
using SGCFT.Apresentacao.Models;
using SGCFT.Dados.Repositorios;
using SGCFT.Dominio.Contratos.Repositorios;
using SGCFT.Dominio.Contratos.Servicos;
using SGCFT.Dominio.Entidades;
using SGCFT.Dominio.Servicos;
using SGCFT.Utilitario;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SGCFT.Apresentacao.Controllers
{
    [Authorize]
    public class ModuloController: BaseController
    {
        private readonly IModuloServico _servicoModulos;
        private readonly ITreinamentoRepositorio _treinamentoRepositorio;
        private readonly IModuloRepositorio _moduloRepositorio;

        public ModuloController()
        {
            _servicoModulos = new ModuloServico(new ModuloRepositorio());
            _treinamentoRepositorio = new TreinamentoRepositorio();
            _moduloRepositorio = new ModuloRepositorio();
        }
        
        [HttpGet]
        [Route("Modulo/GetDropDown/{idTreinamento}")]
        public JsonResult GetDropDown(int idTreinamento)
        {
            var lista = _moduloRepositorio.SelecionarPorIdTreinamento(idTreinamento);
            return Json(lista, JsonRequestBehavior.AllowGet);
        }

        [Route("Modulo/{titulo}/{id}")]
        public ActionResult Exibicao(string titulo, int id)
        {
            var modulo = _moduloRepositorio.ObterModuloPorIdParaExibicao(id, base.IdUsuarioAutenticado);
            var exibicao = new ModuloExibicaoViewModel(modulo.Id, modulo.Titulo, modulo.Videos);
            return View(exibicao);
        }
    }
}

SGCFT.Apresentacao/Controllers/PerguntaController.cs
using SGCFT.Apresentacao.Models;
using SGCFT.Dados.Repositorios;
using SGCFT.Dominio.Contratos.Repositorios;
using SGCFT.Dominio.Contratos.Servicos;
using SGCFT.Dominio.Entidades;
using SGCFT.Dominio.Servicos;
using SGCFT.Utilitario;
using System.Linq;
using System.Web.Mvc;

namespace SGCFT.Apresentacao.Controllers
{
    [Authorize]
    public class PerguntaController: BaseController
    {
        private readonly IPerguntaServico _servicoPerguntas;
        private readonly IPerguntaRepositorio _perguntaRepositorio;
        private readonly ITreinamentoRepositorio _treinamentoRepositorio;
        public PerguntaController()
        {
            _perguntaRepositorio = new PerguntaRepositorio();
            _servicoPerguntas = new PerguntaServico(_perguntaRepositorio);
            _treinamentoRepositorio = new TreinamentoRepositorio();
        }

        public ActionResult Index()
        {
            PerguntaViewModel perguntaViewModel = IniciarCadastro();
            return View(perguntaViewModel);

        }

        [HttpPost]
        public ActionResult Index(PerguntaViewModel perguntaViewModel)
        {
            Retorno retorno = null;
            if (ModelState.IsValid)
            {
                Pergunta pergunta = perguntaViewModel.ConverterParaDominio();
                pergunta.IdAutor = base.IdUsuarioAutenticado;

                for (int i = 0; i < perguntaViewModel.Alternativas.Length; i++)
                {
                    pergunta.AdicionarAlternativa(perguntaViewModel.Alternativas[i], perguntaViewModel.Corretos[i]);
                }

                retorno = _servicoPerguntas.InserirPergunta(pergunta);
                ViewBag.Sucesso = retorno.Sucesso;
                ViewBag.Mensagens = retorno.Mensagens;
            }
            return Json(retorno);
        }

        public JsonResult ObterQuestionario(int idModulo)
        {
            var perguntas = _perguntaRepositorio.SelecionarPorIdModulo(idModulo);
            var questionarios = perguntas.Select(x => new QuestionarioViewModel(x)).ToList();
            return Json(questionarios, JsonRequestBehavior.AllowGet);
        }

        private PerguntaViewModel IniciarCadastro()
        {
            PerguntaViewModel perguntaViewModel = new PerguntaViewModel();
            var treinamentos = _treinamentoRepositorio.selecionarTreinamentosPorUsuario(base.IdUsuarioAutenticado);
            perguntaViewModel.Treinamentos = treinamentos.Select(x => new TreinamentoViewModel(x)).ToList();
            return perguntaViewModel;
        }
    }
}

SGCFT.Apresentacao/Controllers/RespostaController.cs
using SGCFT.Apresentacao.Models;
using SGCFT.Dados.Repositorios;
using SGCFT.Dominio.Contratos.Servicos;
using SGCFT.Dominio.Entidades;
using SGCFT.Dominio.Servicos;
using SGCFT.Utilitario;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SGCFT.Apresentacao.Controllers
{
    public class RespostaController: BaseController
    {
        private readonly IRespostaServico _servicoRespostas;

        public RespostaController()
        {
            _servicoRespostas = new RespostaServico(new RespostaRepositorio(), new AlternativaRepositorio());
        }

        [HttpPost]
        public ActionResult EnvioAlternativa(RespostaViewModel respostaViewModel)
        {
            var respostas = respostaViewModel.ConverterParaRespostas(base.IdUsuarioAutenticado);
            var retornosRespostas = new List<Retorno>();
            foreach (var resposta in respostas)
            {
                var retorno = _servicoRespostas.InserirResposta(resposta);
                retornosRespostas.Add(retorno);
            }

            var resultadoRespostas = _servicoRespostas.SelecionarResultadoQuestionario(respostas.Select(x => x.Id).ToList());

            return Json(new { Erro = retornosRespostas.Any(x => !x.Sucesso), Resultado = resultadoRespostas });
        }
    }
}

SGCFT.Apresentacao/Controllers/VideoController.cs
using SGCFT.Apresentacao.Models;
using SGCFT.Dados.Repositorios;
using SGCFT.Dominio.Contratos.Repositorios;
using SGCFT.Dominio.Contratos.Servicos;
using SGCFT.Dominio.Entidades;
using SGCFT.Dominio.Servicos;
using SGCFT.Utilitario;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace SGCFT.Apresentacao.Controllers
{
    [Authorize]
    public class VideoController: BaseController
    {
        private readonly IVideoServico _servicoVideos;
        private readonly ITreinamentoRepositorio _treinamentoRepositorio;
        private readonly IVideoRepositorio _videoRepositorio;

        public VideoController()
        {
            _servicoVideos = new VideoServico(new VideoRepositorio());
            _treinamentoRepositorio = new TreinamentoRepositorio();
            _videoRepositorio = new VideoRepositorio();
        }

        public ActionResult Index()
        {
            VideoViewModel videoViewModel = IniciarCadastro();
            return View(videoViewModel);
        }

        private VideoViewModel IniciarCadastro()
        {
            VideoViewModel videoViewModel = new VideoViewModel();
            var treinamentos = _treinamentoRepositorio.selecionarTreinamentosPorUsuario(base.IdUsuarioAutenticado);
            videoViewModel.Treinamentos = treinamentos.Select(x => new TreinamentoViewModel(x)).ToList();
            return videoViewModel;
        }

        [HttpPost]
        public ActionResult Index(VideoViewModel videoViewModel)
        {
            if (ModelState.IsValid)
            {
                Video video = videoViewModel.ConverterParaDominio();
                Retorno retorno = _servicoVideos.InserirVideo(video);
                ViewBag.Sucesso = retorno.Sucesso;
                ViewBag.Mensagens = retorno.Mensagens;
            }
            var videoViewModelNovo = IniciarCadastro();
            return View(videoViewModelNovo);
        }

        [HttpGet]
        [Route("Video/modulo-{modulo}/{idModulo}")]
        public ActionResult Exibicao(string modulo, int idModulo)
        {
            var video = _videoRepositorio.ObterVideoPorIdModulo(idModulo);

            object retorno = null;// new TreinamentoExibicaoViewModel(video.Id, video.Modulo.Treinamento.Tema, video.Modulo.Titulo, video.Titulo, video.IdModulo);

            return View(retorno);
        }

        [HttpGet]
        [Route("Video/conteudo/{titulo}/{id}")]
        public FileResult ExibirConteudo(string titulo, int id)
        {
            var video = _videoRepositorio.ObterConteudoVideoPorId(id);
            return File(video, "video/mp4", $"{titulo}.mp4");
        }

    }
}

SGCFT.Apresentacao/Views/Modulo/Exibicao.cshtml
@model SGCFT.Apresentacao.Models.ModuloExibicaoViewModel
@{
    ViewBag.Title = $"Módulo: {Model.Titulo}";
}

@section scripts {
    @Scripts.Render("~/bundles/unobtrusive")
    <script type="text/javascript">
        var link = '@Url.Action("ExibirConteudo", "Video", new { titulo = "titulo", id = "identificador" })';
        var questionarios = [];
        $(document).ready(function () {
            $("#loading").remove();
            $(".page").removeClass("page");

            $("#btnFecharModalPerguntas").click(function () {
                $("#modal-questionario").modal('hide');
            });
        });

        function trocarvideo(titulo, id) {
            var novoLink = link;
            novoLink = novoLink.replace("titulo", titulo);
            novoLink = novoLink.replace("identificador", id);
            $(".list-group-item").removeClass("active");
            $("#video-" + id).addClass("active");
            $("#videosModulo").html('<source src="' + novoLink + '" type="video/mp4"><source src="mov_bbb.ogg" type="video/ogg">Your browser does not support HTML5 video.');
            $("#videosModulo")[0].load();
            $("#videosModulo")[0].play();
        }

        function exibirQuestionario() {
            var urlQuestionario = '@Url.Action("ObterQuestionario", "Pergunta", new { idModulo = "trocar" })';
            urlQuestionario = urlQuestionario.replace("trocar", $("#hddIdModulo").val());
                $.ajax({
                    type: 'GET',
                    url: urlQuestionario,
                    cache: false,
                    success: function (retorno) {
                        questionarios = retorno;
                        $("#conteudo-modal").html("");
                        for (var i = 0; i < retorno.length; i++) {
                            var template = document.getElementById('template-questionario').innerHTML;
                            template = template.replace('{{Pergunta}}', retorno[i].Pergunta);
                            template = template.replace('{{IdPergunta}}', retorno[i].IdPergunta);
                            template = template.replace('{{Indice}}', i);
                            var alternativas = "";
                            for (var j = 0; j < retorno[i].Alternativas.length; j++) {
                                var templateAlternativa = document.getElementById('template-alternativa').innerHTML;
                                templateAlternativa = templateAlternativa.replace("{{Indice}}", i);
                                templateAlternativa = templateAlternativa.replace("{{Id}}", retorno[i].Alternativas[j].Id);
                                templateAlternativa = templateAlternativa.replace("{{Id}}", retorno[i].Alternativas[j].Id);
                                templateAlternativa = templateAlternativa.replace("{{Alternativa}}", retorno[i].Alternativas[j].Texto);
                                alternativas = alternativas + templateAlternativa;
                            }
                            template = template.replace('{{Alternativas}}', alternativas);
                            $("#conteudo-modal").append(template);
                        }
                        $("#modal-questionario").modal('toggle');
                    },
                    error: function (retorno) {
                        $("#card-body-video").append('<div class="alert alert-danger" role="alert">Erro ao obter o questionário</div>');
                    }
                });
        }

        function sucessoResposta(retorno) {
            if (retorno.Erro) {
                alert('Erro não esperado ao enviar suas respostas');
            } else {
                $(retorno.Resultado).each(function () {
                    var elemento = $("#alternativa_" + this.IdAlternativaCorreta);
                    elemento.addClass("sucesso-resposta");
                    if (!this.Acertou) {
                        var elementoEscolhido = $("#alternativa_" + this.IdAlternativaEscolhida);
                        elementoEscolhido.addClass("falha-resposta");
                    }
                });
            }
        }

        function falhaResposta(retorno) {
            alert('nook');
        }

        function enviar() {
            $("#formResposta").submit();
        }

    </script>
}

<section class="section section-xl bg-accent">
    <div class="container">
        <div class="row row-50 justify-content-center flex-lg-row-reverse align-items-center justify-content-lg-between">
            <div class="col-sm-10 col-lg-5 wow fadeInRightSmall">
                <div class="container">
                    <h3 class="text-center">@Model.Titulo</h3>
                    @Html.HiddenFor(x => x.Id, new { id = "hddIdModulo" })
                    <div class="list-group">
                        @for (int i = 0; i < Model.Videos.Count; i++)
                        {
                            if (i == 0)
                            {
                                <a id="video-@Model.Videos[i].Id" href="#" class="list-group-item list-group-item-action active" onclick="trocarvideo('@Model.Videos[i].Titulo', '@Model.Videos[i].Id');">
                                    @Model.Videos[i].Titulo
                                </a>
                            }
                            else
                            {
                                <a id="video-@Model.Videos[i].Id" href="#" class="list-group-item list-group-item-action" onclick="trocarvideo('@Model.Videos[i].Titulo', '@Model.Videos[i].Id');">
                                    @Model.Videos[i].Titulo
                                </a>
                            }
                        }
                        <a id="questionario" href="javascript:void(0);" class="list-group-item list-group-item-action" onclick="exibirQuestionario();">
                            Questionário do módulo
                        </a>
                    </div>
                </div>
            </div>
            <div class="col-sm-10 col-lg-6 wow fadeInLeftSmall">
                <h3 class="text-center">@Model.Videos.First().Titulo</h3>
                <video width="570" height="400" controls id="videosModulo">
                    <source src="@Url.Action("ExibirConteudo", "Video", new { titulo = Model.Videos.First().Titulo, id = Model.Videos.First().Id })" type="video/mp4">
                    <source src="mov_bbb.ogg" type="video/ogg">
                    Your browser does not support HTML5 video.
                </video>
            </div>
        </div>
    </div>
</section>


<div class="modal fade" id="modal-questionario" role="dialog" data-backdrop="static" tabindex="-1" data-keyboard="false" aria-labelledby="questionario">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="col-12 modal-title text-center">Questionário do módulo: @Model.Titulo</h4>
            </div>
            <div class="modal-body">
                @using (Ajax.BeginForm("EnvioAlternativa", "Resposta", new { }, new AjaxOptions() { HttpMethod = "POST", OnSuccess = "sucessoResposta", OnFailure = "falhaResposta" }, new { id = "formResposta", @class = "rd-form" }))
                {
                    <div id="conteudo-modal">
                    </div>
                }

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-sm btn-outline-secondary" data-dismiss="modal" aria-label="Cancelar operação" id="btnFecharModalPerguntas">
                    <i class="fas fa-times-circle"></i> Cancelar
                </button>
                <button type="button" class="btn btn-sm btn-outline-success" id="btnEnviar" onclick="enviar(this);" aria-label="Confirmar operação">
                    <i class="fas fa-trash-alt"></i> Enviar
                </button>
            </div>
        </div>
    </div>
</div>

<script type="text/template" id="template-questionario">
    <div class="form-row" style="margin-bottom: 15px;">
        <div class="col-8 offset-2" style="border-bottom:1px solid silver; padding-bottom: 10px;">
            <h4 class="text-center" style="font-weight:bold;">
                {{Pergunta}}
                <input type="hidden" name="IdsPergunta[{{Indice}}]" value="{{IdPergunta}}" aria-label="Alternativa">
            </h4>
            <div class="form-group">
                {{Alternativas}}
            </div>

        </div>
    </div>
</script>

<script type="text/template" id="template-alternativa">
    <div class="input-group" id="alternativa_{{Id}}">
        <div class="input-group-prepend">
            <div class="input-group-text">
                <input type="radio" name="IdsAlternativasEscolhida[{{Indice}}]" value="{{Id}}" aria-label="Alternativa">
            </div>
        </div>
        <span style="border: 1px solid #e9ecef;padding: 5px;border-radius: 0.25rem;width: 90%;">{{Alternativa}}</span>
    </div>
    <br />
</script>